algoritmo "semnome"
// Função :
// Autor :
// Data : 22/08/2025
// Seção de Declarações
var
nome, sexo  :caracter
inicio
// Seção de Comandos

Escreva("Digite seu nome: ")
Leia(nome)
Escreva("Digite seu sexo(feminino ou masculino): ")
Leia(sexo)
se sexo="Feminino" entao
   Escreval("Ilma Sra ",nome,", Seja Bem Vinda!")

   se sexo="masculino" entao
      Escreval("Ilma Sro ",nome,", Seja Bem Vindo!")

   fimse
fimse
fimalgoritmo
